/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.rastiehaiev

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

class IrDumpPluginTest {

    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.github.rastiehaiev.ir-dump")

        // Verify the result
        assertNotNull(project.tasks.findByName("irCreateOutputDir"))
    }
}
